~/utilities/run_mopac.csh "1-Myoglobin (1M6C).arc"
~/utilities/run_mopac.csh "3CLpro inhibitor (4MDS).arc"
~/utilities/run_mopac.csh "Acyltransferase_(1LXA).arc"
~/utilities/run_mopac.csh "Alpha Tropomyosin (2B9C).arc"
~/utilities/run_mopac.csh "Aromatase (3EQM).arc"
~/utilities/run_mopac.csh "Azurin ISO-2 (1CUO).arc"
~/utilities/run_mopac.csh "Bacteriochlorophyll (4BCL).arc"
~/utilities/run_mopac.csh "Bacteriorhodopsin (1AP9).arc"
~/utilities/run_mopac.csh "Bacteriorhodopsin (1AT9).arc"
~/utilities/run_mopac.csh "Bacteriorhodopsin (1BRX).arc"
~/utilities/run_mopac.csh "Bacteriorhodopsin (1C3W).arc"
~/utilities/run_mopac.csh "Bacteriorhodopsin (2AT9).arc"
~/utilities/run_mopac.csh "Barnase (1RNB).arc"
~/utilities/run_mopac.csh "Bovine lactoferrin (1SDX).arc"
~/utilities/run_mopac.csh "Calmodulin (2F3Y).arc"
~/utilities/run_mopac.csh "Carbonic anhydrase (1RZE).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 1).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 10).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 2).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 3).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 4).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 5).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 6).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 7).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 8).arc"
~/utilities/run_mopac.csh "Cardioactive peptide (1V46)(Model 9).arc"
~/utilities/run_mopac.csh "Chymotrypsin (1AFQ).arc"
~/utilities/run_mopac.csh "Chymotrypsin (8GCH).arc"
~/utilities/run_mopac.csh "Cobalamin (2V3N).arc"
~/utilities/run_mopac.csh "Coiled Coil (2V66).arc"
~/utilities/run_mopac.csh "Collagen-like peptide (1A3J).arc"
~/utilities/run_mopac.csh "Collagenase (1NQJ).arc"
~/utilities/run_mopac.csh "Crambin (1CBN).arc"
~/utilities/run_mopac.csh "Crambin (1EJG).arc"
~/utilities/run_mopac.csh "Crystallin (1AMM).arc"
~/utilities/run_mopac.csh "Cytochrome-C (1CPQ).arc"
~/utilities/run_mopac.csh "Cytochrome-P450 (1DT6).arc"
~/utilities/run_mopac.csh "DMSO Reductase (1DMS).arc"
~/utilities/run_mopac.csh "Flavodoxin (1RCF).arc"
~/utilities/run_mopac.csh "Green fluorescent protein (1EMA).arc"
~/utilities/run_mopac.csh "Green fluorescent protein (1GFL).arc"
~/utilities/run_mopac.csh "Hen egg white lysozyme (193L).arc"
~/utilities/run_mopac.csh "Hen egg white lysozyme (1IEE).arc"
~/utilities/run_mopac.csh "Hexokinase with glucose (2E2O).arc"
~/utilities/run_mopac.csh "Human Cathepsin G (1T32).arc"
~/utilities/run_mopac.csh "Human MTH1 (3ZR0).arc"
~/utilities/run_mopac.csh "Hydrophobin HFBII (2B97).arc"
~/utilities/run_mopac.csh "Importin_(1QGK).arc"
~/utilities/run_mopac.csh "Kemp elimination (KE07).arc"
~/utilities/run_mopac.csh "Metalloprotein (1J3F).arc"
~/utilities/run_mopac.csh "Mouse sulfotransferase sult1d1 (2ZPT).arc"
~/utilities/run_mopac.csh "Outer surface protein (2G8C).arc"
~/utilities/run_mopac.csh "Oxalate decarboxylase (1UW8).arc"
~/utilities/run_mopac.csh "Oxy-Hemoglobin (1GZX).arc"
~/utilities/run_mopac.csh "Pancreatic trypsin inhibitor (1G6X).arc"
~/utilities/run_mopac.csh "Papain (1PE6).arc"
~/utilities/run_mopac.csh "Papain (9PAP).arc"
~/utilities/run_mopac.csh "Pheromone binding protein (1DQE).arc"
~/utilities/run_mopac.csh "Potassium channel (1JVM).arc"
~/utilities/run_mopac.csh "QacR-Diamidine complexes (1RKW).arc"
~/utilities/run_mopac.csh "QacR-Diamidine complexes (1RPW).arc"
~/utilities/run_mopac.csh "Ranasmurfin (2VH3).arc"
~/utilities/run_mopac.csh "Rho (1A62).arc"
~/utilities/run_mopac.csh "Ricin A plus B (2AAI).arc"
~/utilities/run_mopac.csh "Silk (Poly-(Gly-Ala)).arc"
~/utilities/run_mopac.csh "Spectrin (2SPC).arc"
~/utilities/run_mopac.csh "Stage V sporulation protein T (2W1R).arc"
~/utilities/run_mopac.csh "Tetrameric beta-beta-alpha mini-protein (1SN9).arc"
~/utilities/run_mopac.csh "Thermal Hysteresis Protein Isoform YL-1 (1EZG).arc"
~/utilities/run_mopac.csh "Triose Phosphate Isomerase (1WYI).arc"
~/utilities/run_mopac.csh "Triose Phosphate Isomerase (2YPI).arc"
~/utilities/run_mopac.csh "Turkey egg white lysozyme (135L).arc"
~/utilities/run_mopac.csh "Yeast Chorismate Mutase (3CSM).arc"
~/utilities/run_mopac.csh "Zinc Finger (2J7J).arc"
~/utilities/run_mopac.csh "Zinc Finger (3ZNF).arc"
~/utilities/run_mopac.csh "Zinc endoprotease (1C7K).arc"
~/utilities/run_mopac.csh "Zinc-bundle (1EF4).arc"
