~/Utilities/Run_MOPAC.csh "Zinc-bundle (1EF4).mop" 
~/Utilities/Run_MOPAC.csh "Zinc Finger (3ZNF).mop" 
~/Utilities/Run_MOPAC.csh "Zinc Finger (2J7J).mop" 
~/Utilities/Run_MOPAC.csh "Zinc endoprotease (1C7K).mop" 
~/Utilities/Run_MOPAC.csh "Yeast Chorismate Mutase (3CSM).mop" 
~/Utilities/Run_MOPAC.csh "Turkey egg white lysozyme (135L).mop" 
~/Utilities/Run_MOPAC.csh "Triose Phosphate Isomerase (2YPI).mop" 
~/Utilities/Run_MOPAC.csh "Triose Phosphate Isomerase (1WYI).mop" 
~/Utilities/Run_MOPAC.csh "Thermal Hysteresis Protein Isoform YL-1 (1EZG).mop" 
~/Utilities/Run_MOPAC.csh "Tetrameric beta-beta-alpha mini-protein (1SN9).mop" 
~/Utilities/Run_MOPAC.csh "Stage V sporulation protein T (2W1R).mop" 
~/Utilities/Run_MOPAC.csh "Spectrin (2SPC).mop" 
~/Utilities/Run_MOPAC.csh "Silk (Poly-(Gly-Ala)).mop" 
~/Utilities/Run_MOPAC.csh "Ricin A plus B (2AAI).mop" 
~/Utilities/Run_MOPAC.csh "Rho (1A62).mop" 
~/Utilities/Run_MOPAC.csh "Ranasmurfin (2VH3).mop" 
~/Utilities/Run_MOPAC.csh "QacR-Diamidine complexes (1RPW).mop" 
~/Utilities/Run_MOPAC.csh "QacR-Diamidine complexes (1RKW).mop" 
~/Utilities/Run_MOPAC.csh "Potassium channel (1JVM).mop" 
~/Utilities/Run_MOPAC.csh "Pheromone binding protein (1DQE).mop" 
~/Utilities/Run_MOPAC.csh "Papain (9PAP).mop" 
~/Utilities/Run_MOPAC.csh "Papain (1PE6).mop" 
~/Utilities/Run_MOPAC.csh "Pancreatic trypsin inhibitor (1G6X).mop" 
~/Utilities/Run_MOPAC.csh "Oxy-Hemoglobin (1GZX).mop" 
~/Utilities/Run_MOPAC.csh "Oxalate decarboxylase (1UW8).mop" 
~/Utilities/Run_MOPAC.csh "Outer surface protein (2G8C).mop" 
~/Utilities/Run_MOPAC.csh "Mouse sulfotransferase sult1d1 (2ZPT).mop" 
~/Utilities/Run_MOPAC.csh "Metalloprotein (1J3F).mop" 
~/Utilities/Run_MOPAC.csh "Kemp elimination (KE07).mop" 
~/Utilities/Run_MOPAC.csh "Importin_(1QGK).mop" 
~/Utilities/Run_MOPAC.csh "Hydrophobin HFBII (2B97).mop" 
~/Utilities/Run_MOPAC.csh "Human MTH1 (3ZR0).mop" 
~/Utilities/Run_MOPAC.csh "Human Cathepsin G (1T32).mop" 
~/Utilities/Run_MOPAC.csh "Hexokinase with glucose (2E2O).mop" 
~/Utilities/Run_MOPAC.csh "Hen egg white lysozyme (1IEE).mop" 
~/Utilities/Run_MOPAC.csh "Hen egg white lysozyme (193L).mop" 
~/Utilities/Run_MOPAC.csh "Green fluorescent protein (1GFL).mop" 
~/Utilities/Run_MOPAC.csh "Green fluorescent protein (1EMA).mop" 
~/Utilities/Run_MOPAC.csh "Flavodoxin (1RCF).mop" 
~/Utilities/Run_MOPAC.csh "DMSO Reductase (1DMS).mop" 
~/Utilities/Run_MOPAC.csh "Cytochrome-P450 (1DT6).mop" 
~/Utilities/Run_MOPAC.csh "Cytochrome-C (1CPQ).mop" 
~/Utilities/Run_MOPAC.csh "Crystallin (1AMM).mop" 
~/Utilities/Run_MOPAC.csh "Crambin (1EJG).mop" 
~/Utilities/Run_MOPAC.csh "Crambin (1CBN).mop" 
~/Utilities/Run_MOPAC.csh "Collagen-like peptide (1A3J).mop" 
~/Utilities/Run_MOPAC.csh "Collagenase (1NQJ).mop" 
~/Utilities/Run_MOPAC.csh "Coiled Coil (2V66).mop" 
~/Utilities/Run_MOPAC.csh "Cobalamin (2V3N).mop" 
~/Utilities/Run_MOPAC.csh "Chymotrypsin (8GCH).mop" 
~/Utilities/Run_MOPAC.csh "Chymotrypsin (1AFQ).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 9).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 8).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 7).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 6).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 5).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 4).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 3).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 2).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 10).mop" 
~/Utilities/Run_MOPAC.csh "Cardioactive peptide (1V46)(Model 1).mop" 
~/Utilities/Run_MOPAC.csh "Carbonic anhydrase (1RZE).mop" 
~/Utilities/Run_MOPAC.csh "Calmodulin (2F3Y).mop" 
~/Utilities/Run_MOPAC.csh "Bovine lactoferrin (1SDX).mop" 
~/Utilities/Run_MOPAC.csh "Barnase (1RNB).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriorhodopsin (2AT9).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriorhodopsin (1C3W).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriorhodopsin (1BRX).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriorhodopsin (1AT9).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriorhodopsin (1AP9).mop" 
~/Utilities/Run_MOPAC.csh "Bacteriochlorophyll (4BCL).mop" 
~/Utilities/Run_MOPAC.csh "Azurin ISO-2 (1CUO).mop" 
~/Utilities/Run_MOPAC.csh "Aromatase (3EQM).mop" 
~/Utilities/Run_MOPAC.csh "Alpha Tropomyosin (2B9C).mop" 
~/Utilities/Run_MOPAC.csh "Acyltransferase_(1LXA).mop" 
~/Utilities/Run_MOPAC.csh "3CLpro inhibitor (4MDS).mop" 
~/Utilities/Run_MOPAC.csh "1-Myoglobin (1M6C).mop" 
