edit_arc_file "Zinc-bundle (1EF4).arc"
edit_arc_file "Zinc Finger (3ZNF).arc"
edit_arc_file "Zinc Finger (2J7J).arc"
edit_arc_file "Zinc endoprotease (1C7K).arc"
edit_arc_file "Yeast Chorismate Mutase (3CSM).arc"
edit_arc_file "Turkey egg white lysozyme (135L).arc"
edit_arc_file "Triose Phosphate Isomerase (2YPI).arc"
edit_arc_file "Triose Phosphate Isomerase (1WYI).arc"
edit_arc_file "Thermal Hysteresis Protein Isoform YL-1 (1EZG).arc"
edit_arc_file "Tetrameric beta-beta-alpha mini-protein (1SN9).arc"
edit_arc_file "Stage V sporulation protein T (2W1R).arc"
edit_arc_file "Spectrin (2SPC).arc"
edit_arc_file "Silk (Poly-(Gly-Ala)).arc"
edit_arc_file "Ricin A plus B (2AAI).arc"
edit_arc_file "Rho (1A62).arc"
edit_arc_file "Ranasmurfin (2VH3).arc"
edit_arc_file "QacR-Diamidine complexes (1RPW).arc"
edit_arc_file "QacR-Diamidine complexes (1RKW).arc"
edit_arc_file "Potassium channel (1JVM).arc"
edit_arc_file "Pheromone binding protein (1DQE).arc"
edit_arc_file "Papain (9PAP).arc"
edit_arc_file "Papain (1PE6).arc"
edit_arc_file "Pancreatic trypsin inhibitor (1G6X).arc"
edit_arc_file "Oxy-Hemoglobin (1GZX).arc"
edit_arc_file "Oxalate decarboxylase (1UW8).arc"
edit_arc_file "Outer surface protein (2G8C).arc"
edit_arc_file "Mouse sulfotransferase sult1d1 (2ZPT).arc"
edit_arc_file "Metalloprotein (1J3F).arc"
edit_arc_file "Kemp elimination (KE07).arc"
edit_arc_file "Importin_(1QGK).arc"
edit_arc_file "Hydrophobin HFBII (2B97).arc"
edit_arc_file "Human MTH1 (3ZR0).arc"
edit_arc_file "Human Cathepsin G (1T32).arc"
edit_arc_file "Hexokinase with glucose (2E2O).arc"
edit_arc_file "Hen egg white lysozyme (1IEE).arc"
edit_arc_file "Hen egg white lysozyme (193L).arc"
edit_arc_file "Green fluorescent protein (1GFL).arc"
edit_arc_file "Green fluorescent protein (1EMA).arc"
edit_arc_file "Flavodoxin (1RCF).arc"
edit_arc_file "DMSO Reductase (1DMS).arc"
edit_arc_file "Cytochrome-P450 (1DT6).arc"
edit_arc_file "Cytochrome-C (1CPQ).arc"
edit_arc_file "Crystallin (1AMM).arc"
edit_arc_file "Crambin (1EJG).arc"
edit_arc_file "Crambin (1CBN).arc"
edit_arc_file "Collagen-like peptide (1A3J).arc"
edit_arc_file "Collagenase (1NQJ).arc"
edit_arc_file "Coiled Coil (2V66).arc"
edit_arc_file "Cobalamin (2V3N).arc"
edit_arc_file "Chymotrypsin (8GCH).arc"
edit_arc_file "Chymotrypsin (1AFQ).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 9).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 8).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 7).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 6).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 5).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 4).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 3).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 2).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 10).arc"
edit_arc_file "Cardioactive peptide (1V46)(Model 1).arc"
edit_arc_file "Carbonic anhydrase (1RZE).arc"
edit_arc_file "Calmodulin (2F3Y).arc"
edit_arc_file "Bovine lactoferrin (1SDX).arc"
edit_arc_file "Barnase (1RNB).arc"
edit_arc_file "Bacteriorhodopsin (2AT9).arc"
edit_arc_file "Bacteriorhodopsin (1C3W).arc"
edit_arc_file "Bacteriorhodopsin (1BRX).arc"
edit_arc_file "Bacteriorhodopsin (1AT9).arc"
edit_arc_file "Bacteriorhodopsin (1AP9).arc"
edit_arc_file "Bacteriochlorophyll (4BCL).arc"
edit_arc_file "Azurin ISO-2 (1CUO).arc"
edit_arc_file "Aromatase (3EQM).arc"
edit_arc_file "Alpha Tropomyosin (2B9C).arc"
edit_arc_file "Acyltransferase_(1LXA).arc"
edit_arc_file "3CLpro inhibitor (4MDS).arc"
edit_arc_file "1-Myoglobin (1M6C).arc"
